@startuml WinRect
struct WinDrawing.WinRect <<sealed>> <<record>>  {
    + X : double <<get>> <<set>>
    + Y : double <<get>> <<set>>
    + Width : double <<get>> <<set>>
    + Height : double <<get>> <<set>>
}
@enduml